const IATA_TZ: Record<string, string> = {
  LHR: "Europe/London", LGW: "Europe/London", STN: "Europe/London", MAN: "Europe/London",
  EDI: "Europe/London",
  CDG: "Europe/Paris", ORY: "Europe/Paris", AMS: "Europe/Amsterdam",
  FRA: "Europe/Berlin", MUC: "Europe/Berlin",
  FCO: "Europe/Rome", MXP: "Europe/Rome", NAP: "Europe/Rome",
  MAD: "Europe/Madrid", BCN: "Europe/Madrid",
  LIS: "Europe/Lisbon", ZRH: "Europe/Zurich", GVA: "Europe/Zurich",
  VIE: "Europe/Vienna", PRG: "Europe/Prague", WAW: "Europe/Warsaw",
  DUB: "Europe/Dublin", BRU: "Europe/Brussels",
  ATH: "Europe/Athens", CPH: "Europe/Copenhagen",
  HEL: "Europe/Helsinki", OSL: "Europe/Oslo", ARN: "Europe/Stockholm",
  IST: "Europe/Istanbul", SAW: "Europe/Istanbul", AYT: "Europe/Istanbul",
  KEF: "Atlantic/Reykjavik",
  JFK: "America/New_York", EWR: "America/New_York", LGA: "America/New_York",
  BOS: "America/New_York", MIA: "America/New_York", FLL: "America/New_York",
  ATL: "America/New_York", CLT: "America/New_York", PHL: "America/New_York",
  IAD: "America/New_York", DCA: "America/New_York", BWI: "America/New_York",
  RDU: "America/New_York", CHS: "America/New_York", PIT: "America/New_York",
  DTW: "America/New_York", MCO: "America/New_York", TPA: "America/New_York",
  IND: "America/Indiana/Indianapolis",
  ORD: "America/Chicago", DFW: "America/Chicago", IAH: "America/Chicago",
  MSP: "America/Chicago", BNA: "America/Chicago", STL: "America/Chicago",
  MCI: "America/Chicago", AUS: "America/Chicago",
  DEN: "America/Denver", SLC: "America/Denver", PHX: "America/Phoenix",
  LAX: "America/Los_Angeles", SFO: "America/Los_Angeles", SEA: "America/Los_Angeles",
  SAN: "America/Los_Angeles", PDX: "America/Los_Angeles",
  OAK: "America/Los_Angeles", SJC: "America/Los_Angeles",
  HNL: "Pacific/Honolulu",
  YYZ: "America/Toronto", YUL: "America/Toronto", YOW: "America/Toronto",
  YVR: "America/Vancouver", YYC: "America/Edmonton",
  DXB: "Asia/Dubai", AUH: "Asia/Dubai", DOH: "Asia/Qatar",
  RUH: "Asia/Riyadh", JED: "Asia/Riyadh",
  SIN: "Asia/Singapore", HKG: "Asia/Hong_Kong", BKK: "Asia/Bangkok",
  HND: "Asia/Tokyo", NRT: "Asia/Tokyo", KIX: "Asia/Tokyo",
  CTS: "Asia/Tokyo", NGO: "Asia/Tokyo", FUK: "Asia/Tokyo",
  ICN: "Asia/Seoul", GMP: "Asia/Seoul", PUS: "Asia/Seoul",
  DPS: "Asia/Makassar", KUL: "Asia/Kuala_Lumpur",
  TPE: "Asia/Taipei", MNL: "Asia/Manila", CGK: "Asia/Jakarta",
  PEK: "Asia/Shanghai", PVG: "Asia/Shanghai",
  DEL: "Asia/Kolkata", BOM: "Asia/Kolkata",
  SYD: "Australia/Sydney", MEL: "Australia/Melbourne",
  ACC: "Africa/Accra", LOS: "Africa/Lagos", NBO: "Africa/Nairobi",
  ADD: "Africa/Addis_Ababa", CAI: "Africa/Cairo",
  JNB: "Africa/Johannesburg", CPT: "Africa/Johannesburg",
  CMN: "Africa/Casablanca", RAK: "Africa/Casablanca",
  MLE: "Indian/Maldives", MRU: "Indian/Mauritius",
  NAN: "Pacific/Fiji", AKL: "Pacific/Auckland",
  MEX: "America/Mexico_City", CUN: "America/Cancun",
  GRU: "America/Sao_Paulo", GIG: "America/Sao_Paulo",
  EZE: "America/Argentina/Buenos_Aires", BOG: "America/Bogota",
  LIM: "America/Lima", SCL: "America/Santiago",
};

export function airportTz(iata: string): string | undefined {
  if (!iata) return undefined;
  return IATA_TZ[iata.toUpperCase()];
}
